# NumPy Initialization

In [1]:
import numpy

In [ ]:
numpy.array([1, 2, 3])

In [ ]:
from numpy import *

In [ ]:
array([1, 2, 3])

In [2]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
np.__version__

'1.23.1'

In [5]:
array1 = np.arange(100000)
array1

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [ ]:
array2 = list(range(100000))

In [ ]:
%time for i in range(10): my_array1 = array1*2

In [ ]:
%time for i in range(10): my_array2 = [x*2 for x in array2]

In [ ]:
help()

In [ ]:
help(np.sort)

In [ ]:
from numpy import doc

In [ ]:
help(doc)

In [ ]:
help(np.doc.basics)

In [ ]:
np.lookfor('arange')

In [ ]:
np?

In [ ]:
np.arange?

In [ ]:
np.arange??

In [ ]:
np.arange() 

In [ ]:
np.arange