# Pseudorandom Number Generation

In [5]:
import numpy as np

In [6]:
samples1 = np.random.randn(5)
samples1

array([ 1.28951706,  1.21092765, -0.61812034,  0.81627734,  2.69080205])

In [7]:
np.random.randn()

-0.3853974333104986

In [8]:
samples2 = np.random.randn(2, 3)
samples2

array([[ 1.4197755 , -0.22322353, -0.03450196],
       [-0.33158507,  0.20564545,  1.10188377]])

In [9]:
np.random.randn(2, 3, 2)

array([[[ 0.82727546, -0.63866998],
        [-0.18259519,  0.65142862],
        [ 1.07687328, -0.18632957]],

       [[-1.85593132, -0.45673803],
        [ 1.4013924 ,  0.73841913],
        [ 0.40897603,  0.14682642]]])

In [10]:
samples3 = np.random.normal(size=(4, 4))
samples3

array([[-1.30819138,  0.13925173,  1.10557096, -0.3578173 ],
       [-0.72679911,  0.93298396, -1.31500938,  1.34335506],
       [-0.77425025, -1.22163317, -1.5745617 ,  0.82989842],
       [ 1.6678974 ,  0.19158369, -0.02736789, -0.33687784]])

In [11]:
from numpy.random import *

In [12]:
seed(1234)

In [13]:
seed(1234)
x = randn(10)
x

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [14]:
y =rand(10)
y

array([0.68346294, 0.71270203, 0.37025075, 0.56119619, 0.50308317,
       0.01376845, 0.77282662, 0.88264119, 0.36488598, 0.61539618])

In [15]:
z = randint(10, 20)
z

10

In [16]:
zs = randint(10, 30, size=(2, 5), dtype='int64' ) # use float to convert integers in to float values
zs

array([[13, 12, 29, 22, 11],
       [21, 29, 21, 27, 24]], dtype=int64)

In [17]:
randint(10, 30).reshape(2, 10)

AttributeError: 'int' object has no attribute 'reshape'

In [18]:
randn(10).reshape(2, 5)

array([[ 1.05317489,  0.1942955 ,  1.35835198, -0.28694235,  0.44143825],
       [-0.76987271, -0.97456841,  0.70900741, -0.10578273,  0.77677573]])

In [19]:
rand = RandomState(1234)

In [20]:
rand.rand(10)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [21]:
rand.randint(10)

8

In [22]:
rand.randn(10)

array([ 2.00254961,  0.01086208, -0.86924706,  1.4249841 ,  0.1458091 ,
        2.89409095, -0.30426018,  0.861661  , -0.68992667,  0.18749737])

In [30]:
rand.normal(10)

10.194295499906255

In [31]:
rand.uniform(10)

6.0744391849388855